### PR TITLE
Updated and standardized code and file structure to match current SN ext standards.

### PR DESCRIPTION
**Pull request by xthursdayx**
I updated and standardized the directory structure and code to match the current Standard Notes themes formatting, and also created a tagged release to allow for the inclusion of this theme in the [Standard Notes Extensions Self-Hosted Repository](https://github.com/iganeshk/standardnotes-extensions). I'll be happy to correct the repo links in the `ext.json` file (and elsewhere) if this PR is merged (replacing `xthursdayx`, which is there temporarily to get this repo to work with SN, with `Lissy93`.

### CODE REVIEW

**Review by lissy93 — APPROVED** [review]
Awesome! Thanks very much, all really good changes 🙌

**Comment by xthursdayx** [comment]
This is coming quite late, but I just realized that I forgot to mention that you'll need to create a tagged release (`1.0.3`) to match the `callisto-theme.json` that was included in this PR. Sorry about that. It should still work fine to add the tagged release now.

**Comment by lissy93** [comment]
Thanks, I should probably add a GH action to automate this, but in the meantime, I've pushed a new release - [1.0.3](https://github.com/Lissy93/callisto-theme-standard-notes/releases/tag/1.0.3) :)

**Comment by xthursdayx** [comment]
Thanks!

**Pull request merged**
